### ISSUE TITLE
Installation issue relating to re-encoding

### ISSUE THREAD

**Issue by sammo3182** [iqss-research/readme-software#2]
I'm encountering an installation issue and appreciate any suggestions or comments on this, given the so little info I can get from the error message. I already followed the instruction in Readme to install `tensorflow` and every dependencies. Here's the error I got: 

```
Installing package into ‘D:/userLib’
(as ‘lib’ is unspecified)
* installing *source* package 'readme' ...
** using staged installation
** R
Error : (converted from warning) unable to re-encode 'readme2_helper_fxns.R' line 49
ERROR: unable to collate and parse R files for package 'readme'
* removing 'D:/userLib/readme'
Error: Failed to install 'readme' from GitHub:
  (converted from warning) installation of package ‘D:/Rtemp/RtmpyUmcig/file695c53855042/readme_2.0.tar.gz’ had non-zero exit status
```

I'm working on a Win10 (there seems no problem to download as #1 mentioned, though). Here's the `sessioninfo`:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3            
 [2] rstudioapi_0.10.0-9003
 [3] magrittr_1.5          
 [4] usethis_1.5.1         
 [5] devtools_2.2.1        
 [6] pkgload_1.0.2         
 [7] R6_2.4.1              
 [8] rlang_0.4.2           
 [9] tools_3.6.1           
[10] pkgbuild_1.0.6        
[11] sessioninfo_1.1.1     
[12] cli_1.1.0             
[13] withr_2.1.2           
[14] ellipsis_0.3.0        
[15] remotes_2.1.0         
[16] assertthat_0.2.1      
[17] digest_0.6.23         
[18] rprojroot_1.3-2       
[19] crayon_1.3.4          
[20] processx_3.4.1        
[21] callr_3.3.2           
[22] fs_1.3.1              
[23] ps_1.3.0              
[24] curl_4.3              
[25] testthat_2.3.1        
[26] memoise_1.1.0         
[27] glue_1.3.1.9000       
[28] compiler_3.6.1        
[29] desc_1.2.0            
[30] backports_1.1.5       
[31] prettyunits_1.0.2  
```

**Comment by sammo3182** [comment]
It looks like the problem came from 

```r
my_text <- gsub(my_text, pattern = "<3", replace = " ♥ ")
```

I guess the ♥ should be replaced by "<heart>"?

**Comment by cjerzak** [comment]
Hello!

Thank you for your message. Yes, we are going to provide an update very
shortly which resolves this problem by allowing users to specify the text
encoding they wish to use in the pre-processing. We will also provide
tensorflow 2.0 compatibility.

Thank you again and we will be in touch shortly with an update.

Best wishes,

Connor

**Comment by cjerzak** [comment]
Hello,

Thank you again for your message. The Github repository for the readme
software has been updated and this issue (we believe) has been fixed. We
also now have tensorflow 2.0 capabilities.

Let us know if you have any questions or comments, and thank you very much
for reaching out,

Connor

**Comment by sammo3182** [comment]
The new version still does not fix the problem. The building was stuck at line 49, the " ♥ " character. The `try` function does not work, since the computer wouldn't run it at all as long as there's an unrecognized character in the line. I downloaded the package files locally, changed the " ♥ " to "<heart>" as suggested in https://github.com/iqss-research/readme-software/issues/2#issuecomment-566798269, and the package was installed w.o. any problem.

**Comment by cjerzak** [comment]
Interesting -- thank you for this information. We've removed the heart
character from the code to avoid this issue going forward. The latest
version should be working. Thank you again and best wishes for the new
year,

Connor
